// Code generated by go generate; DO NOT EDIT.
package fiscal

var sectorJSONKinds = map[string]string{
	"AddDetalle":                          "array",
	"WithCostosGastosInternacionales":     "object",
	"WithCostosGastosNacionales":          "object",
	"WithNumeroDescripcionPaquetesBultos": "object",
}
