// Fiscal sector schema for the supported go-siat v2.1.1 contract.
// This explicit data has no runtime dependency on the SDK.
package fiscal

var catalogoSectores = []*SectorProfile{
	{
		Codigo:               1,
		Nombre:               "Compra y Venta",
		Layout:               "",
		TipoFacturaDocumento: 1,
		Operacion:            0,
		Fachada:              1,
		ConDetalle:           true,
		DetalleUnico:         false,
		DetallePar:           false,
		Soportado:            true,
		MontoSujetoIvaCero:   false,
		Campos: []CampoSector{
			{JSON: "cafc", Metodo: "WithCafc", Tipo: "string", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "codigo_excepcion", Metodo: "WithCodigoExcepcion", Tipo: "int", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "descuento_adicional", Metodo: "WithDescuentoAdicional", Tipo: "float", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "monto_gift_card", Metodo: "WithMontoGiftCard", Tipo: "float", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "monto_total_sujeto_iva", Metodo: "WithMontoTotalSujetoIva", Tipo: "float", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "numero_tarjeta", Metodo: "WithNumeroTarjeta", Tipo: "int", Requerido: false, Etiqueta: "", Ejemplo: ""},
		},
		CamposDetalle: []CampoSector{
			{JSON: "numero_imei", Metodo: "WithNumeroImei", Tipo: "string", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "numero_serie", Metodo: "WithNumeroSerie", Tipo: "string", Requerido: false, Etiqueta: "", Ejemplo: ""},
		},
	},
	{
		Codigo:               2,
		Nombre:               "Alquiler de Bienes Inmuebles",
		Layout:               "",
		TipoFacturaDocumento: 1,
		Operacion:            0,
		Fachada:              0,
		ConDetalle:           true,
		DetalleUnico:         false,
		DetallePar:           false,
		Soportado:            true,
		MontoSujetoIvaCero:   false,
		Campos: []CampoSector{
			{JSON: "periodo_facturado", Metodo: "WithPeriodoFacturado", Tipo: "string", Requerido: true, Etiqueta: "Período facturado", Ejemplo: "2026-08"},
			{JSON: "cafc", Metodo: "WithCafc", Tipo: "string", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "codigo_excepcion", Metodo: "WithCodigoExcepcion", Tipo: "int", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "descuento_adicional", Metodo: "WithDescuentoAdicional", Tipo: "float", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "monto_total_sujeto_iva", Metodo: "WithMontoTotalSujetoIva", Tipo: "float", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "numero_tarjeta", Metodo: "WithNumeroTarjeta", Tipo: "int", Requerido: false, Etiqueta: "", Ejemplo: ""},
		},
	},
	{
		Codigo:               3,
		Nombre:               "Comercial de Exportación",
		Layout:               "",
		TipoFacturaDocumento: 2,
		Operacion:            0,
		Fachada:              0,
		ConDetalle:           true,
		DetalleUnico:         false,
		DetallePar:           false,
		Soportado:            true,
		MontoSujetoIvaCero:   false,
		Campos: []CampoSector{
			{JSON: "cafc", Metodo: "WithCafc", Tipo: "string", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "codigo_excepcion", Metodo: "WithCodigoExcepcion", Tipo: "int", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "codigo_pais", Metodo: "WithCodigoPais", Tipo: "int", Requerido: true, Etiqueta: "", Ejemplo: ""},
			{JSON: "costos_gastos_internacionales", Metodo: "WithCostosGastosInternacionales", Tipo: "json", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "costos_gastos_nacionales", Metodo: "WithCostosGastosNacionales", Tipo: "json", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "descuento_adicional", Metodo: "WithDescuentoAdicional", Tipo: "float", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "direccion_comprador", Metodo: "WithDireccionComprador", Tipo: "string", Requerido: true, Etiqueta: "", Ejemplo: ""},
			{JSON: "incoterm", Metodo: "WithIncoterm", Tipo: "string", Requerido: true, Etiqueta: "", Ejemplo: ""},
			{JSON: "incoterm_detalle", Metodo: "WithIncotermDetalle", Tipo: "string", Requerido: true, Etiqueta: "", Ejemplo: ""},
			{JSON: "informacion_adicional", Metodo: "WithInformacionAdicional", Tipo: "string", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "lugar_destino", Metodo: "WithLugarDestino", Tipo: "string", Requerido: true, Etiqueta: "", Ejemplo: ""},
			{JSON: "monto_detalle", Metodo: "WithMontoDetalle", Tipo: "float", Requerido: true, Etiqueta: "", Ejemplo: ""},
			{JSON: "monto_total_sujeto_iva", Metodo: "WithMontoTotalSujetoIva", Tipo: "float", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "numero_descripcion_paquetes_bultos", Metodo: "WithNumeroDescripcionPaquetesBultos", Tipo: "json", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "numero_tarjeta", Metodo: "WithNumeroTarjeta", Tipo: "int", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "puerto_destino", Metodo: "WithPuertoDestino", Tipo: "string", Requerido: true, Etiqueta: "", Ejemplo: ""},
			{JSON: "total_gastos_internacionales", Metodo: "WithTotalGastosInternacionales", Tipo: "float", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "total_gastos_nacionales_fob", Metodo: "WithTotalGastosNacionalesFob", Tipo: "float", Requerido: true, Etiqueta: "", Ejemplo: ""},
		},
		CamposDetalle: []CampoSector{
			{JSON: "codigo_nandina", Metodo: "WithCodigoNandina", Tipo: "string", Requerido: true, Etiqueta: "", Ejemplo: ""},
		},
	},
	{
		Codigo:               4,
		Nombre:               "Libre Consignación",
		Layout:               "",
		TipoFacturaDocumento: 2,
		Operacion:            0,
		Fachada:              0,
		ConDetalle:           true,
		DetalleUnico:         false,
		DetallePar:           false,
		Soportado:            true,
		MontoSujetoIvaCero:   false,
		Campos: []CampoSector{
			{JSON: "cafc", Metodo: "WithCafc", Tipo: "string", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "codigo_excepcion", Metodo: "WithCodigoExcepcion", Tipo: "int", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "codigo_pais", Metodo: "WithCodigoPais", Tipo: "int", Requerido: true, Etiqueta: "", Ejemplo: ""},
			{JSON: "monto_total_sujeto_iva", Metodo: "WithMontoTotalSujetoIva", Tipo: "float", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "numero_tarjeta", Metodo: "WithNumeroTarjeta", Tipo: "int", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "puerto_destino", Metodo: "WithPuertoDestino", Tipo: "string", Requerido: true, Etiqueta: "", Ejemplo: ""},
		},
		CamposDetalle: []CampoSector{
			{JSON: "codigo_nandina", Metodo: "WithCodigoNandina", Tipo: "string", Requerido: true, Etiqueta: "", Ejemplo: ""},
		},
	},
	{
		Codigo:               5,
		Nombre:               "Venta en Zona Franca",
		Layout:               "",
		TipoFacturaDocumento: 2,
		Operacion:            0,
		Fachada:              0,
		ConDetalle:           true,
		DetalleUnico:         false,
		DetallePar:           false,
		Soportado:            true,
		MontoSujetoIvaCero:   false,
		Campos: []CampoSector{
			{JSON: "cafc", Metodo: "WithCafc", Tipo: "string", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "codigo_excepcion", Metodo: "WithCodigoExcepcion", Tipo: "int", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "descuento_adicional", Metodo: "WithDescuentoAdicional", Tipo: "float", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "monto_gift_card", Metodo: "WithMontoGiftCard", Tipo: "float", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "monto_total_sujeto_iva", Metodo: "WithMontoTotalSujetoIva", Tipo: "float", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "numero_parte_recepcion", Metodo: "WithNumeroParteRecepcion", Tipo: "string", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "numero_tarjeta", Metodo: "WithNumeroTarjeta", Tipo: "int", Requerido: false, Etiqueta: "", Ejemplo: ""},
		},
	},
	{
		Codigo:               6,
		Nombre:               "Servicio Turístico y Hospedaje",
		Layout:               "",
		TipoFacturaDocumento: 2,
		Operacion:            0,
		Fachada:              0,
		ConDetalle:           true,
		DetalleUnico:         false,
		DetallePar:           false,
		Soportado:            true,
		MontoSujetoIvaCero:   false,
		Campos: []CampoSector{
			{JSON: "fecha_ingreso_hospedaje", Metodo: "WithFechaIngresoHospedaje", Tipo: "fecha", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "cantidad_habitaciones", Metodo: "WithCantidadHabitaciones", Tipo: "int", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "cantidad_huespedes", Metodo: "WithCantidadHuespedes", Tipo: "int", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "cantidad_mayores", Metodo: "WithCantidadMayores", Tipo: "int", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "cantidad_menores", Metodo: "WithCantidadMenores", Tipo: "int", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "razon_social_operador_turismo", Metodo: "WithRazonSocialOperadorTurismo", Tipo: "string", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "cafc", Metodo: "WithCafc", Tipo: "string", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "codigo_excepcion", Metodo: "WithCodigoExcepcion", Tipo: "int", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "descuento_adicional", Metodo: "WithDescuentoAdicional", Tipo: "float", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "monto_gift_card", Metodo: "WithMontoGiftCard", Tipo: "float", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "monto_total_sujeto_iva", Metodo: "WithMontoTotalSujetoIva", Tipo: "float", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "numero_tarjeta", Metodo: "WithNumeroTarjeta", Tipo: "int", Requerido: false, Etiqueta: "", Ejemplo: ""},
		},
		CamposDetalle: []CampoSector{
			{JSON: "codigo_tipo_habitacion", Metodo: "WithCodigoTipoHabitacion", Tipo: "int", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "detalle_huespedes", Metodo: "WithDetalleHuespedes", Tipo: "string", Requerido: false, Etiqueta: "", Ejemplo: ""},
		},
	},
	{
		Codigo:               7,
		Nombre:               "Seguridad Alimentaria y Abastecimiento",
		Layout:               "",
		TipoFacturaDocumento: 2,
		Operacion:            0,
		Fachada:              0,
		ConDetalle:           true,
		DetalleUnico:         false,
		DetallePar:           false,
		Soportado:            true,
		MontoSujetoIvaCero:   false,
		Campos: []CampoSector{
			{JSON: "cafc", Metodo: "WithCafc", Tipo: "string", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "codigo_excepcion", Metodo: "WithCodigoExcepcion", Tipo: "int", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "descuento_adicional", Metodo: "WithDescuentoAdicional", Tipo: "float", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "monto_gift_card", Metodo: "WithMontoGiftCard", Tipo: "float", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "numero_tarjeta", Metodo: "WithNumeroTarjeta", Tipo: "int", Requerido: false, Etiqueta: "", Ejemplo: ""},
		},
	},
	{
		Codigo:               8,
		Nombre:               "Tasa Cero (libros y transporte internacional de carga)",
		Layout:               "",
		TipoFacturaDocumento: 2,
		Operacion:            0,
		Fachada:              0,
		ConDetalle:           true,
		DetalleUnico:         false,
		DetallePar:           false,
		Soportado:            true,
		MontoSujetoIvaCero:   true,
		Campos: []CampoSector{
			{JSON: "cafc", Metodo: "WithCafc", Tipo: "string", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "codigo_excepcion", Metodo: "WithCodigoExcepcion", Tipo: "int", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "descuento_adicional", Metodo: "WithDescuentoAdicional", Tipo: "float", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "monto_gift_card", Metodo: "WithMontoGiftCard", Tipo: "float", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "monto_total_sujeto_iva", Metodo: "WithMontoTotalSujetoIva", Tipo: "float", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "numero_tarjeta", Metodo: "WithNumeroTarjeta", Tipo: "int", Requerido: false, Etiqueta: "", Ejemplo: ""},
		},
	},
	{
		Codigo:               9,
		Nombre:               "Compra y Venta de Moneda Extranjera",
		Layout:               "",
		TipoFacturaDocumento: 2,
		Operacion:            0,
		Fachada:              0,
		ConDetalle:           true,
		DetalleUnico:         false,
		DetallePar:           false,
		Soportado:            true,
		MontoSujetoIvaCero:   false,
		Campos: []CampoSector{
			{JSON: "codigo_tipo_operacion", Metodo: "WithCodigoTipoOperacion", Tipo: "int", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "tipo_cambio_oficial", Metodo: "WithTipoCambioOficial", Tipo: "float", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "ingreso_diferencia_cambio", Metodo: "WithIngresoDiferenciaCambio", Tipo: "float", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "cafc", Metodo: "WithCafc", Tipo: "string", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "codigo_excepcion", Metodo: "WithCodigoExcepcion", Tipo: "int", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "descuento_adicional", Metodo: "WithDescuentoAdicional", Tipo: "float", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "monto_total_sujeto_iva", Metodo: "WithMontoTotalSujetoIva", Tipo: "float", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "numero_tarjeta", Metodo: "WithNumeroTarjeta", Tipo: "int", Requerido: false, Etiqueta: "", Ejemplo: ""},
		},
	},
	{
		Codigo:               10,
		Nombre:               "Dutty Free",
		Layout:               "",
		TipoFacturaDocumento: 2,
		Operacion:            0,
		Fachada:              0,
		ConDetalle:           true,
		DetalleUnico:         false,
		DetallePar:           false,
		Soportado:            true,
		MontoSujetoIvaCero:   false,
		Campos: []CampoSector{
			{JSON: "cafc", Metodo: "WithCafc", Tipo: "string", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "codigo_excepcion", Metodo: "WithCodigoExcepcion", Tipo: "int", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "descuento_adicional", Metodo: "WithDescuentoAdicional", Tipo: "float", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "monto_gift_card", Metodo: "WithMontoGiftCard", Tipo: "float", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "monto_total_sujeto_iva", Metodo: "WithMontoTotalSujetoIva", Tipo: "float", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "numero_tarjeta", Metodo: "WithNumeroTarjeta", Tipo: "int", Requerido: false, Etiqueta: "", Ejemplo: ""},
		},
	},
	{
		Codigo:               11,
		Nombre:               "Sectores Educativos",
		Layout:               "",
		TipoFacturaDocumento: 1,
		Operacion:            0,
		Fachada:              0,
		ConDetalle:           true,
		DetalleUnico:         false,
		DetallePar:           false,
		Soportado:            true,
		MontoSujetoIvaCero:   false,
		Campos: []CampoSector{
			{JSON: "nombre_estudiante", Metodo: "WithNombreEstudiante", Tipo: "string", Requerido: true, Etiqueta: "Nombre del estudiante", Ejemplo: "Juan Pérez"},
			{JSON: "periodo_facturado", Metodo: "WithPeriodoFacturado", Tipo: "string", Requerido: true, Etiqueta: "Período facturado", Ejemplo: "2026-08"},
			{JSON: "cafc", Metodo: "WithCafc", Tipo: "string", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "codigo_excepcion", Metodo: "WithCodigoExcepcion", Tipo: "int", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "descuento_adicional", Metodo: "WithDescuentoAdicional", Tipo: "float", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "monto_gift_card", Metodo: "WithMontoGiftCard", Tipo: "float", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "monto_total_sujeto_iva", Metodo: "WithMontoTotalSujetoIva", Tipo: "float", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "numero_tarjeta", Metodo: "WithNumeroTarjeta", Tipo: "int", Requerido: false, Etiqueta: "", Ejemplo: ""},
		},
	},
	{
		Codigo:               12,
		Nombre:               "Comercialización de Hidrocarburos",
		Layout:               "",
		TipoFacturaDocumento: 1,
		Operacion:            0,
		Fachada:              0,
		ConDetalle:           true,
		DetalleUnico:         false,
		DetallePar:           false,
		Soportado:            true,
		MontoSujetoIvaCero:   false,
		Campos: []CampoSector{
			{JSON: "cafc", Metodo: "WithCafc", Tipo: "string", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "codigo_autorizacion_sc", Metodo: "WithCodigoAutorizacionSC", Tipo: "string", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "codigo_excepcion", Metodo: "WithCodigoExcepcion", Tipo: "int", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "codigo_pais", Metodo: "WithCodigoPais", Tipo: "int", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "descuento_adicional", Metodo: "WithDescuentoAdicional", Tipo: "float", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "monto_total_sujeto_iva", Metodo: "WithMontoTotalSujetoIva", Tipo: "float", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "numero_tarjeta", Metodo: "WithNumeroTarjeta", Tipo: "int", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "observacion", Metodo: "WithObservacion", Tipo: "string", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "placa_vehiculo", Metodo: "WithPlacaVehiculo", Tipo: "string", Requerido: true, Etiqueta: "", Ejemplo: ""},
			{JSON: "tipo_envase", Metodo: "WithTipoEnvase", Tipo: "string", Requerido: false, Etiqueta: "", Ejemplo: ""},
		},
	},
	{
		Codigo:               13,
		Nombre:               "Servicios Básicos",
		Layout:               "",
		TipoFacturaDocumento: 1,
		Operacion:            0,
		Fachada:              3,
		ConDetalle:           true,
		DetalleUnico:         false,
		DetallePar:           false,
		Soportado:            true,
		MontoSujetoIvaCero:   false,
		Campos: []CampoSector{
			{JSON: "numero_medidor", Metodo: "WithNumeroMedidor", Tipo: "string", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "consumo_periodo", Metodo: "WithConsumoPeriodo", Tipo: "float", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "ciudad", Metodo: "WithCiudad", Tipo: "string", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "zona", Metodo: "WithZona", Tipo: "string", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "gestion", Metodo: "WithGestion", Tipo: "int", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "mes", Metodo: "WithMes", Tipo: "string", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "ajuste_no_sujeto_iva", Metodo: "WithAjusteNoSujetoIva", Tipo: "float", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "ajuste_sujeto_iva", Metodo: "WithAjusteSujetoIva", Tipo: "float", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "beneficiario_ley1886", Metodo: "WithBeneficiarioLey1886", Tipo: "int", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "cafc", Metodo: "WithCafc", Tipo: "string", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "codigo_excepcion", Metodo: "WithCodigoExcepcion", Tipo: "int", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "descuento_adicional", Metodo: "WithDescuentoAdicional", Tipo: "float", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "detalle_ajuste_no_sujeto_iva", Metodo: "WithDetalleAjusteNoSujetoIva", Tipo: "string", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "detalle_ajuste_sujeto_iva", Metodo: "WithDetalleAjusteSujetoIva", Tipo: "string", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "detalle_otros_pagos_no_sujeto_iva", Metodo: "WithDetalleOtrosPagosNoSujetoIva", Tipo: "string", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "domicilio_cliente", Metodo: "WithDomicilioCliente", Tipo: "string", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "monto_descuento_ley1886", Metodo: "WithMontoDescuentoLey1886", Tipo: "float", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "monto_descuento_tarifa_dignidad", Metodo: "WithMontoDescuentoTarifaDignidad", Tipo: "float", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "monto_total_sujeto_iva", Metodo: "WithMontoTotalSujetoIva", Tipo: "float", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "numero_tarjeta", Metodo: "WithNumeroTarjeta", Tipo: "int", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "otras_tasas", Metodo: "WithOtrasTasas", Tipo: "float", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "otros_pagos_no_sujeto_iva", Metodo: "WithOtrosPagosNoSujetoIva", Tipo: "float", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "tasa_alumbrado", Metodo: "WithTasaAlumbrado", Tipo: "float", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "tasa_aseo", Metodo: "WithTasaAseo", Tipo: "float", Requerido: false, Etiqueta: "", Ejemplo: ""},
		},
	},
	{
		Codigo:               14,
		Nombre:               "Productos Alcanzados por el ICE",
		Layout:               "",
		TipoFacturaDocumento: 1,
		Operacion:            0,
		Fachada:              0,
		ConDetalle:           true,
		DetalleUnico:         false,
		DetallePar:           false,
		Soportado:            true,
		MontoSujetoIvaCero:   false,
		Campos: []CampoSector{
			{JSON: "cafc", Metodo: "WithCafc", Tipo: "string", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "codigo_excepcion", Metodo: "WithCodigoExcepcion", Tipo: "int", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "descuento_adicional", Metodo: "WithDescuentoAdicional", Tipo: "float", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "monto_ice_especifico", Metodo: "WithMontoIceEspecifico", Tipo: "float", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "monto_ice_porcentual", Metodo: "WithMontoIcePorcentual", Tipo: "float", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "monto_total_sujeto_iva", Metodo: "WithMontoTotalSujetoIva", Tipo: "float", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "numero_tarjeta", Metodo: "WithNumeroTarjeta", Tipo: "int", Requerido: false, Etiqueta: "", Ejemplo: ""},
		},
		CamposDetalle: []CampoSector{
			{JSON: "alicuota_especifica", Metodo: "WithAlicuotaEspecifica", Tipo: "float", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "alicuota_iva", Metodo: "WithAlicuotaIva", Tipo: "float", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "alicuota_porcentual", Metodo: "WithAlicuotaPorcentual", Tipo: "float", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "cantidad_ice", Metodo: "WithCantidadIce", Tipo: "float", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "marca_ice", Metodo: "WithMarcaIce", Tipo: "int", Requerido: true, Etiqueta: "", Ejemplo: ""},
			{JSON: "monto_ice_especifico", Metodo: "WithMontoIceEspecifico", Tipo: "float", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "monto_ice_porcentual", Metodo: "WithMontoIcePorcentual", Tipo: "float", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "precio_neto_venta_ice", Metodo: "WithPrecioNetoVentaIce", Tipo: "float", Requerido: false, Etiqueta: "", Ejemplo: ""},
		},
	},
	{
		Codigo:               15,
		Nombre:               "Entidades Financieras",
		Layout:               "",
		TipoFacturaDocumento: 1,
		Operacion:            0,
		Fachada:              4,
		ConDetalle:           true,
		DetalleUnico:         false,
		DetallePar:           false,
		Soportado:            true,
		MontoSujetoIvaCero:   false,
		Campos: []CampoSector{
			{JSON: "monto_total_arrendamiento_financiero", Metodo: "WithMontoTotalArrendamientoFinanciero", Tipo: "float", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "cafc", Metodo: "WithCafc", Tipo: "string", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "codigo_excepcion", Metodo: "WithCodigoExcepcion", Tipo: "int", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "descuento_adicional", Metodo: "WithDescuentoAdicional", Tipo: "float", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "monto_total_sujeto_iva", Metodo: "WithMontoTotalSujetoIva", Tipo: "float", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "numero_tarjeta", Metodo: "WithNumeroTarjeta", Tipo: "int", Requerido: false, Etiqueta: "", Ejemplo: ""},
		},
	},
	{
		Codigo:               16,
		Nombre:               "Hoteles",
		Layout:               "",
		TipoFacturaDocumento: 1,
		Operacion:            0,
		Fachada:              0,
		ConDetalle:           true,
		DetalleUnico:         false,
		DetallePar:           false,
		Soportado:            true,
		MontoSujetoIvaCero:   false,
		Campos: []CampoSector{
			{JSON: "fecha_ingreso_hospedaje", Metodo: "WithFechaIngresoHospedaje", Tipo: "fecha", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "cantidad_habitaciones", Metodo: "WithCantidadHabitaciones", Tipo: "int", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "cantidad_huespedes", Metodo: "WithCantidadHuespedes", Tipo: "int", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "cantidad_mayores", Metodo: "WithCantidadMayores", Tipo: "int", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "cantidad_menores", Metodo: "WithCantidadMenores", Tipo: "int", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "cafc", Metodo: "WithCafc", Tipo: "string", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "codigo_excepcion", Metodo: "WithCodigoExcepcion", Tipo: "int", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "descuento_adicional", Metodo: "WithDescuentoAdicional", Tipo: "float", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "monto_gift_card", Metodo: "WithMontoGiftCard", Tipo: "float", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "monto_total_sujeto_iva", Metodo: "WithMontoTotalSujetoIva", Tipo: "float", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "numero_tarjeta", Metodo: "WithNumeroTarjeta", Tipo: "int", Requerido: false, Etiqueta: "", Ejemplo: ""},
		},
		CamposDetalle: []CampoSector{
			{JSON: "codigo_tipo_habitacion", Metodo: "WithCodigoTipoHabitacion", Tipo: "int", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "detalle_huespedes", Metodo: "WithDetalleHuespedes", Tipo: "json", Requerido: false, Etiqueta: "", Ejemplo: ""},
		},
	},
	{
		Codigo:               17,
		Nombre:               "Hospitales / Clínicas",
		Layout:               "",
		TipoFacturaDocumento: 1,
		Operacion:            0,
		Fachada:              0,
		ConDetalle:           true,
		DetalleUnico:         false,
		DetallePar:           false,
		Soportado:            true,
		MontoSujetoIvaCero:   false,
		Campos: []CampoSector{
			{JSON: "modalidad_servicio", Metodo: "WithModalidadServicio", Tipo: "string", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "cafc", Metodo: "WithCafc", Tipo: "string", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "codigo_excepcion", Metodo: "WithCodigoExcepcion", Tipo: "int", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "descuento_adicional", Metodo: "WithDescuentoAdicional", Tipo: "float", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "monto_gift_card", Metodo: "WithMontoGiftCard", Tipo: "float", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "monto_total_sujeto_iva", Metodo: "WithMontoTotalSujetoIva", Tipo: "float", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "numero_tarjeta", Metodo: "WithNumeroTarjeta", Tipo: "int", Requerido: false, Etiqueta: "", Ejemplo: ""},
		},
		CamposDetalle: []CampoSector{
			{JSON: "especialidad", Metodo: "WithEspecialidad", Tipo: "string", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "especialidad_detalle", Metodo: "WithEspecialidadDetalle", Tipo: "string", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "especialidad_medico", Metodo: "WithEspecialidadMedico", Tipo: "string", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "nit_documento_medico", Metodo: "WithNitDocumentoMedico", Tipo: "int", Requerido: true, Etiqueta: "", Ejemplo: ""},
			{JSON: "nombre_apellido_medico", Metodo: "WithNombreApellidoMedico", Tipo: "string", Requerido: true, Etiqueta: "", Ejemplo: ""},
			{JSON: "nro_factura_medico", Metodo: "WithNroFacturaMedico", Tipo: "int", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "nro_matricula_medico", Metodo: "WithNroMatriculaMedico", Tipo: "string", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "nro_quirofano_sala_operaciones", Metodo: "WithNroQuirofanoSalaOperaciones", Tipo: "int", Requerido: true, Etiqueta: "", Ejemplo: ""},
		},
	},
	{
		Codigo:               18,
		Nombre:               "Juegos de Azar",
		Layout:               "",
		TipoFacturaDocumento: 1,
		Operacion:            0,
		Fachada:              0,
		ConDetalle:           true,
		DetalleUnico:         false,
		DetallePar:           false,
		Soportado:            true,
		MontoSujetoIvaCero:   false,
		Campos: []CampoSector{
			{JSON: "cafc", Metodo: "WithCafc", Tipo: "string", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "codigo_excepcion", Metodo: "WithCodigoExcepcion", Tipo: "int", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "descuento_adicional", Metodo: "WithDescuentoAdicional", Tipo: "float", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "monto_total_ij", Metodo: "WithMontoTotalIj", Tipo: "float", Requerido: true, Etiqueta: "", Ejemplo: ""},
			{JSON: "monto_total_sujeto_ipj", Metodo: "WithMontoTotalSujetoIpj", Tipo: "float", Requerido: true, Etiqueta: "", Ejemplo: ""},
			{JSON: "monto_total_sujeto_iva", Metodo: "WithMontoTotalSujetoIva", Tipo: "float", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "numero_tarjeta", Metodo: "WithNumeroTarjeta", Tipo: "int", Requerido: false, Etiqueta: "", Ejemplo: ""},
		},
	},
	{
		Codigo:               19,
		Nombre:               "Hidrocarburos Alcanzada IEHD",
		Layout:               "",
		TipoFacturaDocumento: 1,
		Operacion:            0,
		Fachada:              0,
		ConDetalle:           true,
		DetalleUnico:         false,
		DetallePar:           false,
		Soportado:            true,
		MontoSujetoIvaCero:   false,
		Campos: []CampoSector{
			{JSON: "cafc", Metodo: "WithCafc", Tipo: "string", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "ciudad", Metodo: "WithCiudad", Tipo: "string", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "codigo_excepcion", Metodo: "WithCodigoExcepcion", Tipo: "int", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "condicion_pago", Metodo: "WithCondicionPago", Tipo: "string", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "descuento_adicional", Metodo: "WithDescuentoAdicional", Tipo: "float", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "monto_iehd", Metodo: "WithMontoIehd", Tipo: "float", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "monto_total_sujeto_iva", Metodo: "WithMontoTotalSujetoIva", Tipo: "float", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "nombre_propietario", Metodo: "WithNombrePropietario", Tipo: "string", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "nombre_representante_legal", Metodo: "WithNombreRepresentanteLegal", Tipo: "string", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "numero_tarjeta", Metodo: "WithNumeroTarjeta", Tipo: "int", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "periodo_entrega", Metodo: "WithPeriodoEntrega", Tipo: "string", Requerido: false, Etiqueta: "", Ejemplo: ""},
		},
		CamposDetalle: []CampoSector{
			{JSON: "porcentaje_iehd", Metodo: "WithPorcentajeIehd", Tipo: "float", Requerido: false, Etiqueta: "", Ejemplo: ""},
		},
	},
	{
		Codigo:               20,
		Nombre:               "Comercial de Exportación de Minerales",
		Layout:               "",
		TipoFacturaDocumento: 2,
		Operacion:            0,
		Fachada:              0,
		ConDetalle:           true,
		DetalleUnico:         false,
		DetallePar:           false,
		Soportado:            true,
		MontoSujetoIvaCero:   false,
		Campos: []CampoSector{
			{JSON: "cafc", Metodo: "WithCafc", Tipo: "string", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "codigo_excepcion", Metodo: "WithCodigoExcepcion", Tipo: "int", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "concentrado_granel", Metodo: "WithConcentradoGranel", Tipo: "string", Requerido: true, Etiqueta: "", Ejemplo: ""},
			{JSON: "descuento_adicional", Metodo: "WithDescuentoAdicional", Tipo: "float", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "direccion_comprador", Metodo: "WithDireccionComprador", Tipo: "string", Requerido: true, Etiqueta: "", Ejemplo: ""},
			{JSON: "gastos_realizacion", Metodo: "WithGastosRealizacion", Tipo: "float", Requerido: true, Etiqueta: "", Ejemplo: ""},
			{JSON: "humedad_porcentaje", Metodo: "WithHumedadPorcentaje", Tipo: "float", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "humedad_valor", Metodo: "WithHumedadValor", Tipo: "float", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "incoterm", Metodo: "WithIncoterm", Tipo: "string", Requerido: true, Etiqueta: "", Ejemplo: ""},
			{JSON: "kilos_netos_humedos", Metodo: "WithKilosNetosHumedos", Tipo: "float", Requerido: true, Etiqueta: "", Ejemplo: ""},
			{JSON: "kilos_netos_secos", Metodo: "WithKilosNetosSecos", Tipo: "float", Requerido: true, Etiqueta: "", Ejemplo: ""},
			{JSON: "merma_porcentaje", Metodo: "WithMermaPorcentaje", Tipo: "float", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "merma_valor", Metodo: "WithMermaValor", Tipo: "float", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "monto_total_sujeto_iva", Metodo: "WithMontoTotalSujetoIva", Tipo: "float", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "nim", Metodo: "WithNim", Tipo: "string", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "numero_lote", Metodo: "WithNumeroLote", Tipo: "string", Requerido: true, Etiqueta: "", Ejemplo: ""},
			{JSON: "numero_tarjeta", Metodo: "WithNumeroTarjeta", Tipo: "int", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "origen", Metodo: "WithOrigen", Tipo: "string", Requerido: true, Etiqueta: "", Ejemplo: ""},
			{JSON: "otros_datos", Metodo: "WithOtrosDatos", Tipo: "json", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "pais_destino", Metodo: "WithPaisDestino", Tipo: "int", Requerido: true, Etiqueta: "", Ejemplo: ""},
			{JSON: "puerto_destino", Metodo: "WithPuertoDestino", Tipo: "string", Requerido: true, Etiqueta: "", Ejemplo: ""},
			{JSON: "puerto_transito", Metodo: "WithPuertoTransito", Tipo: "string", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "ruex", Metodo: "WithRuex", Tipo: "string", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "tipo_cambio_anb", Metodo: "WithTipoCambioANB", Tipo: "float", Requerido: true, Etiqueta: "", Ejemplo: ""},
		},
		CamposDetalle: []CampoSector{
			{JSON: "cantidad_extraccion", Metodo: "WithCantidadExtraccion", Tipo: "float", Requerido: true, Etiqueta: "", Ejemplo: ""},
			{JSON: "codigo_nandina", Metodo: "WithCodigoNandina", Tipo: "string", Requerido: true, Etiqueta: "", Ejemplo: ""},
			{JSON: "descripcion_leyes", Metodo: "WithDescripcionLeyes", Tipo: "string", Requerido: true, Etiqueta: "", Ejemplo: ""},
			{JSON: "unidad_medida_extraccion", Metodo: "WithUnidadMedidaExtraccion", Tipo: "int", Requerido: true, Etiqueta: "", Ejemplo: ""},
		},
	},
	{
		Codigo:               21,
		Nombre:               "Venta de Minerales",
		Layout:               "",
		TipoFacturaDocumento: 1,
		Operacion:            0,
		Fachada:              0,
		ConDetalle:           true,
		DetalleUnico:         false,
		DetallePar:           false,
		Soportado:            true,
		MontoSujetoIvaCero:   false,
		Campos: []CampoSector{
			{JSON: "cafc", Metodo: "WithCafc", Tipo: "string", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "codigo_excepcion", Metodo: "WithCodigoExcepcion", Tipo: "int", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "concentrado_granel", Metodo: "WithConcentradoGranel", Tipo: "string", Requerido: true, Etiqueta: "", Ejemplo: ""},
			{JSON: "descuento_adicional", Metodo: "WithDescuentoAdicional", Tipo: "float", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "direccion_comprador", Metodo: "WithDireccionComprador", Tipo: "string", Requerido: true, Etiqueta: "", Ejemplo: ""},
			{JSON: "gastos_realizacion", Metodo: "WithGastosRealizacion", Tipo: "float", Requerido: true, Etiqueta: "", Ejemplo: ""},
			{JSON: "humedad_porcentaje", Metodo: "WithHumedadPorcentaje", Tipo: "float", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "humedad_valor", Metodo: "WithHumedadValor", Tipo: "float", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "incoterm", Metodo: "WithIncoterm", Tipo: "string", Requerido: true, Etiqueta: "", Ejemplo: ""},
			{JSON: "iva", Metodo: "WithIva", Tipo: "float", Requerido: true, Etiqueta: "", Ejemplo: ""},
			{JSON: "kilos_netos_humedos", Metodo: "WithKilosNetosHumedos", Tipo: "float", Requerido: true, Etiqueta: "", Ejemplo: ""},
			{JSON: "kilos_netos_secos", Metodo: "WithKilosNetosSecos", Tipo: "float", Requerido: true, Etiqueta: "", Ejemplo: ""},
			{JSON: "liquidacion_preliminar", Metodo: "WithLiquidacionPreliminar", Tipo: "float", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "merma_porcentaje", Metodo: "WithMermaPorcentaje", Tipo: "float", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "merma_valor", Metodo: "WithMermaValor", Tipo: "float", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "monto_gift_card", Metodo: "WithMontoGiftCard", Tipo: "float", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "monto_total_sujeto_iva", Metodo: "WithMontoTotalSujetoIva", Tipo: "float", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "numero_lote", Metodo: "WithNumeroLote", Tipo: "string", Requerido: true, Etiqueta: "", Ejemplo: ""},
			{JSON: "numero_tarjeta", Metodo: "WithNumeroTarjeta", Tipo: "int", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "origen", Metodo: "WithOrigen", Tipo: "string", Requerido: true, Etiqueta: "", Ejemplo: ""},
			{JSON: "otros_datos", Metodo: "WithOtrosDatos", Tipo: "string", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "pais_destino", Metodo: "WithPaisDestino", Tipo: "int", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "puerto_destino", Metodo: "WithPuertoDestino", Tipo: "string", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "puerto_transito", Metodo: "WithPuertoTransito", Tipo: "string", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "sub_total", Metodo: "WithSubTotal", Tipo: "float", Requerido: true, Etiqueta: "", Ejemplo: ""},
			{JSON: "tipo_cambio_anb", Metodo: "WithTipoCambioANB", Tipo: "float", Requerido: true, Etiqueta: "", Ejemplo: ""},
		},
		CamposDetalle: []CampoSector{
			{JSON: "cantidad_extraccion", Metodo: "WithCantidadExtraccion", Tipo: "float", Requerido: true, Etiqueta: "", Ejemplo: ""},
			{JSON: "codigo_nandina", Metodo: "WithCodigoNandina", Tipo: "string", Requerido: true, Etiqueta: "", Ejemplo: ""},
			{JSON: "descripcion_leyes", Metodo: "WithDescripcionLeyes", Tipo: "string", Requerido: true, Etiqueta: "", Ejemplo: ""},
			{JSON: "unidad_medida_extraccion", Metodo: "WithUnidadMedidaExtraccion", Tipo: "int", Requerido: true, Etiqueta: "", Ejemplo: ""},
		},
	},
	{
		Codigo:               22,
		Nombre:               "Telecomunicaciones",
		Layout:               "",
		TipoFacturaDocumento: 1,
		Operacion:            0,
		Fachada:              2,
		ConDetalle:           true,
		DetalleUnico:         false,
		DetallePar:           false,
		Soportado:            true,
		MontoSujetoIvaCero:   false,
		Campos: []CampoSector{
			{JSON: "nit_conjunto", Metodo: "WithNitConjunto", Tipo: "int", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "cafc", Metodo: "WithCafc", Tipo: "string", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "codigo_excepcion", Metodo: "WithCodigoExcepcion", Tipo: "int", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "descuento_adicional", Metodo: "WithDescuentoAdicional", Tipo: "float", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "monto_gift_card", Metodo: "WithMontoGiftCard", Tipo: "float", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "monto_total_sujeto_iva", Metodo: "WithMontoTotalSujetoIva", Tipo: "float", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "numero_tarjeta", Metodo: "WithNumeroTarjeta", Tipo: "int", Requerido: false, Etiqueta: "", Ejemplo: ""},
		},
		CamposDetalle: []CampoSector{
			{JSON: "numero_imei", Metodo: "WithNumeroImei", Tipo: "string", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "numero_serie", Metodo: "WithNumeroSerie", Tipo: "string", Requerido: false, Etiqueta: "", Ejemplo: ""},
		},
	},
	{
		Codigo:               23,
		Nombre:               "Prevalorada",
		Layout:               "",
		TipoFacturaDocumento: 1,
		Operacion:            0,
		Fachada:              0,
		ConDetalle:           true,
		DetalleUnico:         true,
		DetallePar:           false,
		Soportado:            true,
		MontoSujetoIvaCero:   false,
		Campos: []CampoSector{
			{JSON: "monto_total_sujeto_iva", Metodo: "WithMontoTotalSujetoIva", Tipo: "float", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "numero_tarjeta", Metodo: "WithNumeroTarjeta", Tipo: "int", Requerido: false, Etiqueta: "", Ejemplo: ""},
		},
	},
	{
		Codigo:               24,
		Nombre:               "Nota de Crédito-Débito",
		Layout:               "nota_credito_debito",
		TipoFacturaDocumento: 3,
		Operacion:            1,
		Fachada:              6,
		ConDetalle:           true,
		DetalleUnico:         false,
		DetallePar:           false,
		Soportado:            true,
		MontoSujetoIvaCero:   false,
		Campos: []CampoSector{
			{JSON: "numero_autorizacion_cuf", Metodo: "WithNumeroAutorizacionCuf", Tipo: "string", Requerido: true, Etiqueta: "CUF de la factura original", Ejemplo: "7894561237894561237894561237894561237894561237894561237894561237894561AA"},
			{JSON: "fecha_emision_factura", Metodo: "WithFechaEmisionFactura", Tipo: "fecha", Requerido: true, Etiqueta: "Fecha de emisión de la factura original", Ejemplo: "2026-08-24T00:00:00.000"},
			{JSON: "monto_total_original", Metodo: "WithMontoTotalOriginal", Tipo: "float", Requerido: true, Etiqueta: "Monto total de la factura original", Ejemplo: "100.00"},
			{JSON: "monto_total_devuelto", Metodo: "WithMontoTotalDevuelto", Tipo: "float", Requerido: true, Etiqueta: "Monto devuelto por la nota", Ejemplo: "25.00"},
			{JSON: "monto_efectivo_credito_debito", Metodo: "WithMontoEfectivoCreditoDebito", Tipo: "float", Requerido: true, Etiqueta: "Monto efectivo de la nota", Ejemplo: "75.00"},
			{JSON: "monto_descuento_credito_debito", Metodo: "WithMontoDescuentoCreditoDebito", Tipo: "float", Requerido: false, Etiqueta: "Descuento de la nota", Ejemplo: "0.00"},
			{JSON: "numero_nota_credito_debito", Metodo: "WithNumeroNotaCreditoDebito", Tipo: "int", Requerido: false, Etiqueta: "Número de nota de crédito/débito", Ejemplo: "1"},
			{JSON: "codigo_excepcion", Metodo: "WithCodigoExcepcion", Tipo: "int", Requerido: false, Etiqueta: "", Ejemplo: ""},
		},
	},
	{
		Codigo:               24,
		Nombre:               "Nota Fiscal de Crédito-Débito",
		Layout:               "nota_fiscal_credito_debito",
		TipoFacturaDocumento: 3,
		Operacion:            1,
		Fachada:              6,
		ConDetalle:           true,
		DetalleUnico:         false,
		DetallePar:           false,
		Soportado:            true,
		MontoSujetoIvaCero:   false,
		Campos: []CampoSector{
			{JSON: "numero_autorizacion_cuf", Metodo: "WithNumeroAutorizacionCuf", Tipo: "string", Requerido: true, Etiqueta: "CUF de la factura original", Ejemplo: "7894561237894561237894561237894561237894561237894561237894561237894561AA"},
			{JSON: "fecha_emision_factura", Metodo: "WithFechaEmisionFactura", Tipo: "fecha", Requerido: true, Etiqueta: "Fecha de emisión de la factura original", Ejemplo: "2026-08-24T00:00:00.000"},
			{JSON: "monto_total_original", Metodo: "WithMontoTotalOriginal", Tipo: "float", Requerido: true, Etiqueta: "Monto total de la factura original", Ejemplo: "100.00"},
			{JSON: "monto_total_devuelto", Metodo: "WithMontoTotalDevuelto", Tipo: "float", Requerido: true, Etiqueta: "Monto devuelto por la nota", Ejemplo: "25.00"},
			{JSON: "monto_efectivo_credito_debito", Metodo: "WithMontoEfectivoCreditoDebito", Tipo: "float", Requerido: true, Etiqueta: "Monto efectivo de la nota", Ejemplo: "75.00"},
			{JSON: "monto_descuento_credito_debito", Metodo: "WithMontoDescuentoCreditoDebito", Tipo: "float", Requerido: false, Etiqueta: "Descuento de la nota", Ejemplo: "0.00"},
			{JSON: "numero_nota_credito_debito", Metodo: "WithNumeroNotaCreditoDebito", Tipo: "int", Requerido: false, Etiqueta: "Número de nota de crédito/débito", Ejemplo: "1"},
			{JSON: "codigo_excepcion", Metodo: "WithCodigoExcepcion", Tipo: "int", Requerido: false, Etiqueta: "", Ejemplo: ""},
		},
	},
	{
		Codigo:               28,
		Nombre:               "Comercial de Exportación de Servicios",
		Layout:               "",
		TipoFacturaDocumento: 2,
		Operacion:            0,
		Fachada:              0,
		ConDetalle:           true,
		DetalleUnico:         false,
		DetallePar:           false,
		Soportado:            true,
		MontoSujetoIvaCero:   false,
		Campos: []CampoSector{
			{JSON: "cafc", Metodo: "WithCafc", Tipo: "string", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "codigo_excepcion", Metodo: "WithCodigoExcepcion", Tipo: "int", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "codigo_pais", Metodo: "WithCodigoPais", Tipo: "int", Requerido: true, Etiqueta: "", Ejemplo: ""},
			{JSON: "descuento_adicional", Metodo: "WithDescuentoAdicional", Tipo: "float", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "direccion_comprador", Metodo: "WithDireccionComprador", Tipo: "string", Requerido: true, Etiqueta: "", Ejemplo: ""},
			{JSON: "informacion_adicional", Metodo: "WithInformacionAdicional", Tipo: "string", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "lugar_destino", Metodo: "WithLugarDestino", Tipo: "string", Requerido: true, Etiqueta: "", Ejemplo: ""},
			{JSON: "monto_total_sujeto_iva", Metodo: "WithMontoTotalSujetoIva", Tipo: "float", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "numero_tarjeta", Metodo: "WithNumeroTarjeta", Tipo: "int", Requerido: false, Etiqueta: "", Ejemplo: ""},
		},
	},
	{
		Codigo:               29,
		Nombre:               "Nota de Conciliación",
		Layout:               "",
		TipoFacturaDocumento: 3,
		Operacion:            1,
		Fachada:              6,
		ConDetalle:           true,
		DetalleUnico:         false,
		DetallePar:           false,
		Soportado:            true,
		MontoSujetoIvaCero:   false,
		Campos: []CampoSector{
			{JSON: "numero_autorizacion_cuf", Metodo: "WithNumeroAutorizacionCuf", Tipo: "string", Requerido: true, Etiqueta: "", Ejemplo: ""},
			{JSON: "fecha_emision_factura", Metodo: "WithFechaEmisionFactura", Tipo: "fecha", Requerido: true, Etiqueta: "", Ejemplo: ""},
			{JSON: "monto_total_original", Metodo: "WithMontoTotalOriginal", Tipo: "float", Requerido: true, Etiqueta: "", Ejemplo: ""},
			{JSON: "monto_total_conciliado", Metodo: "WithMontoTotalConciliado", Tipo: "float", Requerido: true, Etiqueta: "", Ejemplo: ""},
			{JSON: "numero_nota_conciliacion", Metodo: "WithNumeroNotaConciliacion", Tipo: "int", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "credito_fiscal_iva", Metodo: "WithCreditoFiscalIva", Tipo: "float", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "debito_fiscal_iva", Metodo: "WithDebitoFiscalIva", Tipo: "float", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "codigo_control", Metodo: "WithCodigoControl", Tipo: "string", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "codigo_excepcion", Metodo: "WithCodigoExcepcion", Tipo: "int", Requerido: false, Etiqueta: "", Ejemplo: ""},
		},
		CamposDetalle: []CampoSector{
			{JSON: "monto_conciliado", Metodo: "WithMontoConciliado", Tipo: "float", Requerido: true, Etiqueta: "", Ejemplo: ""},
			{JSON: "monto_final", Metodo: "WithMontoFinal", Tipo: "float", Requerido: true, Etiqueta: "", Ejemplo: ""},
			{JSON: "monto_original", Metodo: "WithMontoOriginal", Tipo: "float", Requerido: true, Etiqueta: "", Ejemplo: ""},
		},
	},
	{
		Codigo:               30,
		Nombre:               "Boleto Aéreo",
		Layout:               "",
		TipoFacturaDocumento: 2,
		Operacion:            0,
		Fachada:              5,
		ConDetalle:           false,
		DetalleUnico:         false,
		DetallePar:           false,
		Soportado:            true,
		MontoSujetoIvaCero:   false,
		Campos: []CampoSector{
			{JSON: "nombre_pasajero", Metodo: "WithNombrePasajero", Tipo: "string", Requerido: true, Etiqueta: "", Ejemplo: ""},
			{JSON: "numero_documento_pasajero", Metodo: "WithNumeroDocumentoPasajero", Tipo: "string", Requerido: true, Etiqueta: "", Ejemplo: ""},
			{JSON: "codigo_iata_linea_aerea", Metodo: "WithCodigoIataLineaAerea", Tipo: "int", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "codigo_iata_agente_viajes", Metodo: "WithCodigoIataAgenteViajes", Tipo: "string", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "nit_agente_viajes", Metodo: "WithNitAgenteViajes", Tipo: "int", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "codigo_origen_servicio", Metodo: "WithCodigoOrigenServicio", Tipo: "string", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "codigo_tipo_transaccion", Metodo: "WithCodigoTipoTransaccion", Tipo: "string", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "monto_tarifa", Metodo: "WithMontoTarifa", Tipo: "float", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "monto_total_sujeto_iva", Metodo: "WithMontoTotalSujetoIva", Tipo: "float", Requerido: false, Etiqueta: "", Ejemplo: ""},
		},
	},
	{
		Codigo:               31,
		Nombre:               "Suministro de Energía",
		Layout:               "",
		TipoFacturaDocumento: 1,
		Operacion:            0,
		Fachada:              0,
		ConDetalle:           true,
		DetalleUnico:         false,
		DetallePar:           false,
		Soportado:            true,
		MontoSujetoIvaCero:   false,
		Campos: []CampoSector{
			{JSON: "cafc", Metodo: "WithCafc", Tipo: "string", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "codigo_excepcion", Metodo: "WithCodigoExcepcion", Tipo: "int", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "codigo_pais", Metodo: "WithCodigoPais", Tipo: "int", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "descuento_adicional", Metodo: "WithDescuentoAdicional", Tipo: "float", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "monto_gift_card", Metodo: "WithMontoGiftCard", Tipo: "float", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "monto_total_sujeto_iva", Metodo: "WithMontoTotalSujetoIva", Tipo: "float", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "numero_tarjeta", Metodo: "WithNumeroTarjeta", Tipo: "int", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "placa_vehiculo", Metodo: "WithPlacaVehiculo", Tipo: "string", Requerido: true, Etiqueta: "", Ejemplo: ""},
		},
	},
	{
		Codigo:               33,
		Nombre:               "Tasa Cero IVA Ley N° 1613",
		Layout:               "",
		TipoFacturaDocumento: 2,
		Operacion:            0,
		Fachada:              0,
		ConDetalle:           false,
		DetalleUnico:         false,
		DetallePar:           false,
		Soportado:            false,
		MontoSujetoIvaCero:   false,
	},
	{
		Codigo:               34,
		Nombre:               "Seguros",
		Layout:               "",
		TipoFacturaDocumento: 1,
		Operacion:            0,
		Fachada:              0,
		ConDetalle:           true,
		DetalleUnico:         false,
		DetallePar:           false,
		Soportado:            true,
		MontoSujetoIvaCero:   false,
		Campos: []CampoSector{
			{JSON: "ajuste_afectacion_iva", Metodo: "WithAjusteAfectacionIva", Tipo: "float", Requerido: true, Etiqueta: "", Ejemplo: ""},
			{JSON: "cafc", Metodo: "WithCafc", Tipo: "string", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "codigo_excepcion", Metodo: "WithCodigoExcepcion", Tipo: "int", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "descuento_adicional", Metodo: "WithDescuentoAdicional", Tipo: "float", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "monto_gift_card", Metodo: "WithMontoGiftCard", Tipo: "float", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "monto_total_sujeto_iva", Metodo: "WithMontoTotalSujetoIva", Tipo: "float", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "numero_tarjeta", Metodo: "WithNumeroTarjeta", Tipo: "int", Requerido: false, Etiqueta: "", Ejemplo: ""},
		},
	},
	{
		Codigo:               35,
		Nombre:               "Compra Venta Bonificaciones",
		Layout:               "",
		TipoFacturaDocumento: 1,
		Operacion:            0,
		Fachada:              1,
		ConDetalle:           true,
		DetalleUnico:         false,
		DetallePar:           false,
		Soportado:            true,
		MontoSujetoIvaCero:   false,
		Campos: []CampoSector{
			{JSON: "cafc", Metodo: "WithCafc", Tipo: "string", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "codigo_excepcion", Metodo: "WithCodigoExcepcion", Tipo: "int", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "descuento_adicional", Metodo: "WithDescuentoAdicional", Tipo: "float", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "monto_gift_card", Metodo: "WithMontoGiftCard", Tipo: "float", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "monto_total_sujeto_iva", Metodo: "WithMontoTotalSujetoIva", Tipo: "float", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "numero_tarjeta", Metodo: "WithNumeroTarjeta", Tipo: "int", Requerido: false, Etiqueta: "", Ejemplo: ""},
		},
		CamposDetalle: []CampoSector{
			{JSON: "numero_imei", Metodo: "WithNumeroImei", Tipo: "string", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "numero_serie", Metodo: "WithNumeroSerie", Tipo: "string", Requerido: false, Etiqueta: "", Ejemplo: ""},
		},
	},
	{
		Codigo:               36,
		Nombre:               "Prevalorada Sin Derecho a Crédito Fiscal",
		Layout:               "",
		TipoFacturaDocumento: 2,
		Operacion:            0,
		Fachada:              0,
		ConDetalle:           true,
		DetalleUnico:         true,
		DetallePar:           false,
		Soportado:            true,
		MontoSujetoIvaCero:   false,
		Campos: []CampoSector{
			{JSON: "monto_total_sujeto_iva", Metodo: "WithMontoTotalSujetoIva", Tipo: "float", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "numero_tarjeta", Metodo: "WithNumeroTarjeta", Tipo: "int", Requerido: false, Etiqueta: "", Ejemplo: ""},
		},
	},
	{
		Codigo:               37,
		Nombre:               "Comercialización de GNV",
		Layout:               "",
		TipoFacturaDocumento: 1,
		Operacion:            0,
		Fachada:              0,
		ConDetalle:           true,
		DetalleUnico:         false,
		DetallePar:           false,
		Soportado:            true,
		MontoSujetoIvaCero:   false,
		Campos: []CampoSector{
			{JSON: "cafc", Metodo: "WithCafc", Tipo: "string", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "codigo_excepcion", Metodo: "WithCodigoExcepcion", Tipo: "int", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "codigo_pais", Metodo: "WithCodigoPais", Tipo: "int", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "descuento_adicional", Metodo: "WithDescuentoAdicional", Tipo: "float", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "monto_total_sujeto_iva", Metodo: "WithMontoTotalSujetoIva", Tipo: "float", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "monto_vale", Metodo: "WithMontoVale", Tipo: "float", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "numero_tarjeta", Metodo: "WithNumeroTarjeta", Tipo: "int", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "placa_vehiculo", Metodo: "WithPlacaVehiculo", Tipo: "string", Requerido: true, Etiqueta: "", Ejemplo: ""},
			{JSON: "tipo_envase", Metodo: "WithTipoEnvase", Tipo: "string", Requerido: false, Etiqueta: "", Ejemplo: ""},
		},
	},
	{
		Codigo:               38,
		Nombre:               "Hidrocarburos No Alcanzada IEHD",
		Layout:               "",
		TipoFacturaDocumento: 1,
		Operacion:            0,
		Fachada:              0,
		ConDetalle:           true,
		DetalleUnico:         false,
		DetallePar:           false,
		Soportado:            true,
		MontoSujetoIvaCero:   false,
		Campos: []CampoSector{
			{JSON: "cafc", Metodo: "WithCafc", Tipo: "string", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "ciudad", Metodo: "WithCiudad", Tipo: "string", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "codigo_excepcion", Metodo: "WithCodigoExcepcion", Tipo: "int", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "condicion_pago", Metodo: "WithCondicionPago", Tipo: "string", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "descuento_adicional", Metodo: "WithDescuentoAdicional", Tipo: "float", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "monto_total_sujeto_iva", Metodo: "WithMontoTotalSujetoIva", Tipo: "float", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "nombre_propietario", Metodo: "WithNombrePropietario", Tipo: "string", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "nombre_representante_legal", Metodo: "WithNombreRepresentanteLegal", Tipo: "string", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "numero_tarjeta", Metodo: "WithNumeroTarjeta", Tipo: "int", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "periodo_entrega", Metodo: "WithPeriodoEntrega", Tipo: "string", Requerido: false, Etiqueta: "", Ejemplo: ""},
		},
	},
	{
		Codigo:               39,
		Nombre:               "Comercialización de GN y GLP",
		Layout:               "",
		TipoFacturaDocumento: 1,
		Operacion:            0,
		Fachada:              0,
		ConDetalle:           true,
		DetalleUnico:         false,
		DetallePar:           false,
		Soportado:            true,
		MontoSujetoIvaCero:   false,
		Campos: []CampoSector{
			{JSON: "cafc", Metodo: "WithCafc", Tipo: "string", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "codigo_excepcion", Metodo: "WithCodigoExcepcion", Tipo: "int", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "descuento_adicional", Metodo: "WithDescuentoAdicional", Tipo: "float", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "monto_total_sujeto_iva", Metodo: "WithMontoTotalSujetoIva", Tipo: "float", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "numero_tarjeta", Metodo: "WithNumeroTarjeta", Tipo: "int", Requerido: false, Etiqueta: "", Ejemplo: ""},
		},
	},
	{
		Codigo:               40,
		Nombre:               "Servicios Básicos Zona Franca",
		Layout:               "",
		TipoFacturaDocumento: 2,
		Operacion:            0,
		Fachada:              3,
		ConDetalle:           true,
		DetalleUnico:         false,
		DetallePar:           false,
		Soportado:            true,
		MontoSujetoIvaCero:   false,
		Campos: []CampoSector{
			{JSON: "numero_medidor", Metodo: "WithNumeroMedidor", Tipo: "string", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "consumo_periodo", Metodo: "WithConsumoPeriodo", Tipo: "float", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "ciudad", Metodo: "WithCiudad", Tipo: "string", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "zona", Metodo: "WithZona", Tipo: "string", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "gestion", Metodo: "WithGestion", Tipo: "int", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "mes", Metodo: "WithMes", Tipo: "string", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "ajuste_no_sujeto_iva", Metodo: "WithAjusteNoSujetoIva", Tipo: "float", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "ajuste_sujeto_iva", Metodo: "WithAjusteSujetoIva", Tipo: "float", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "beneficiario_ley1886", Metodo: "WithBeneficiarioLey1886", Tipo: "int", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "cafc", Metodo: "WithCafc", Tipo: "string", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "codigo_excepcion", Metodo: "WithCodigoExcepcion", Tipo: "int", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "descuento_adicional", Metodo: "WithDescuentoAdicional", Tipo: "float", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "detalle_ajuste_no_sujeto_iva", Metodo: "WithDetalleAjusteNoSujetoIva", Tipo: "string", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "detalle_ajuste_sujeto_iva", Metodo: "WithDetalleAjusteSujetoIva", Tipo: "string", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "detalle_otros_pagos_no_sujeto_iva", Metodo: "WithDetalleOtrosPagosNoSujetoIva", Tipo: "string", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "domicilio_cliente", Metodo: "WithDomicilioCliente", Tipo: "string", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "monto_descuento_ley1886", Metodo: "WithMontoDescuentoLey1886", Tipo: "float", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "monto_descuento_tarifa_dignidad", Metodo: "WithMontoDescuentoTarifaDignidad", Tipo: "float", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "numero_tarjeta", Metodo: "WithNumeroTarjeta", Tipo: "int", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "otras_tasas", Metodo: "WithOtrasTasas", Tipo: "float", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "otros_pagos_no_sujeto_iva", Metodo: "WithOtrosPagosNoSujetoIva", Tipo: "float", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "tasa_alumbrado", Metodo: "WithTasaAlumbrado", Tipo: "float", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "tasa_aseo", Metodo: "WithTasaAseo", Tipo: "float", Requerido: false, Etiqueta: "", Ejemplo: ""},
		},
	},
	{
		Codigo:               41,
		Nombre:               "Compra Venta Tasas",
		Layout:               "",
		TipoFacturaDocumento: 1,
		Operacion:            0,
		Fachada:              1,
		ConDetalle:           true,
		DetalleUnico:         false,
		DetallePar:           false,
		Soportado:            true,
		MontoSujetoIvaCero:   false,
		Campos: []CampoSector{
			{JSON: "cafc", Metodo: "WithCafc", Tipo: "string", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "codigo_excepcion", Metodo: "WithCodigoExcepcion", Tipo: "int", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "descuento_adicional", Metodo: "WithDescuentoAdicional", Tipo: "float", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "monto_gift_card", Metodo: "WithMontoGiftCard", Tipo: "float", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "monto_tasa", Metodo: "WithMontoTasa", Tipo: "float", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "monto_total_sujeto_iva", Metodo: "WithMontoTotalSujetoIva", Tipo: "float", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "numero_tarjeta", Metodo: "WithNumeroTarjeta", Tipo: "int", Requerido: false, Etiqueta: "", Ejemplo: ""},
		},
		CamposDetalle: []CampoSector{
			{JSON: "numero_imei", Metodo: "WithNumeroImei", Tipo: "string", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "numero_serie", Metodo: "WithNumeroSerie", Tipo: "string", Requerido: false, Etiqueta: "", Ejemplo: ""},
		},
	},
	{
		Codigo:               42,
		Nombre:               "Alquiler Zona Franca",
		Layout:               "",
		TipoFacturaDocumento: 2,
		Operacion:            0,
		Fachada:              0,
		ConDetalle:           true,
		DetalleUnico:         false,
		DetallePar:           false,
		Soportado:            true,
		MontoSujetoIvaCero:   false,
		Campos: []CampoSector{
			{JSON: "periodo_facturado", Metodo: "WithPeriodoFacturado", Tipo: "string", Requerido: true, Etiqueta: "Período facturado", Ejemplo: "2026-08"},
			{JSON: "cafc", Metodo: "WithCafc", Tipo: "string", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "codigo_excepcion", Metodo: "WithCodigoExcepcion", Tipo: "int", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "descuento_adicional", Metodo: "WithDescuentoAdicional", Tipo: "float", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "monto_total_sujeto_iva", Metodo: "WithMontoTotalSujetoIva", Tipo: "float", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "numero_tarjeta", Metodo: "WithNumeroTarjeta", Tipo: "int", Requerido: false, Etiqueta: "", Ejemplo: ""},
		},
	},
	{
		Codigo:               43,
		Nombre:               "Comercial de Exportación Hidrocarburos",
		Layout:               "",
		TipoFacturaDocumento: 2,
		Operacion:            0,
		Fachada:              0,
		ConDetalle:           true,
		DetalleUnico:         false,
		DetallePar:           false,
		Soportado:            true,
		MontoSujetoIvaCero:   false,
		Campos: []CampoSector{
			{JSON: "cafc", Metodo: "WithCafc", Tipo: "string", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "codigo_excepcion", Metodo: "WithCodigoExcepcion", Tipo: "int", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "codigo_pais", Metodo: "WithCodigoPais", Tipo: "int", Requerido: true, Etiqueta: "", Ejemplo: ""},
			{JSON: "costos_gastos_internacionales", Metodo: "WithCostosGastosInternacionales", Tipo: "json", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "costos_gastos_nacionales", Metodo: "WithCostosGastosNacionales", Tipo: "json", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "descuento_adicional", Metodo: "WithDescuentoAdicional", Tipo: "float", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "direccion_comprador", Metodo: "WithDireccionComprador", Tipo: "string", Requerido: true, Etiqueta: "", Ejemplo: ""},
			{JSON: "incoterm", Metodo: "WithIncoterm", Tipo: "string", Requerido: true, Etiqueta: "", Ejemplo: ""},
			{JSON: "incoterm_detalle", Metodo: "WithIncotermDetalle", Tipo: "string", Requerido: true, Etiqueta: "", Ejemplo: ""},
			{JSON: "informacion_adicional", Metodo: "WithInformacionAdicional", Tipo: "string", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "lugar_destino", Metodo: "WithLugarDestino", Tipo: "string", Requerido: true, Etiqueta: "", Ejemplo: ""},
			{JSON: "monto_detalle", Metodo: "WithMontoDetalle", Tipo: "float", Requerido: true, Etiqueta: "", Ejemplo: ""},
			{JSON: "monto_total_sujeto_iva", Metodo: "WithMontoTotalSujetoIva", Tipo: "float", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "numero_descripcion_paquetes_bultos", Metodo: "WithNumeroDescripcionPaquetesBultos", Tipo: "json", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "numero_tarjeta", Metodo: "WithNumeroTarjeta", Tipo: "int", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "puerto_destino", Metodo: "WithPuertoDestino", Tipo: "string", Requerido: true, Etiqueta: "", Ejemplo: ""},
			{JSON: "total_gastos_internacionales", Metodo: "WithTotalGastosInternacionales", Tipo: "float", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "total_gastos_nacionales_fob", Metodo: "WithTotalGastosNacionalesFob", Tipo: "float", Requerido: true, Etiqueta: "", Ejemplo: ""},
		},
		CamposDetalle: []CampoSector{
			{JSON: "codigo_nandina", Metodo: "WithCodigoNandina", Tipo: "string", Requerido: true, Etiqueta: "", Ejemplo: ""},
		},
	},
	{
		Codigo:               44,
		Nombre:               "Importación y Comercialización de Lubricantes",
		Layout:               "",
		TipoFacturaDocumento: 1,
		Operacion:            0,
		Fachada:              0,
		ConDetalle:           true,
		DetalleUnico:         false,
		DetallePar:           false,
		Soportado:            true,
		MontoSujetoIvaCero:   false,
		Campos: []CampoSector{
			{JSON: "cafc", Metodo: "WithCafc", Tipo: "string", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "ciudad", Metodo: "WithCiudad", Tipo: "string", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "codigo_excepcion", Metodo: "WithCodigoExcepcion", Tipo: "int", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "condicion_pago", Metodo: "WithCondicionPago", Tipo: "string", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "descuento_adicional", Metodo: "WithDescuentoAdicional", Tipo: "float", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "monto_deduccion_iehd_ds25530", Metodo: "WithMontoDeduccionIehdDS25530", Tipo: "float", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "monto_total_sujeto_iva", Metodo: "WithMontoTotalSujetoIva", Tipo: "float", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "nombre_propietario", Metodo: "WithNombrePropietario", Tipo: "string", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "nombre_representante_legal", Metodo: "WithNombreRepresentanteLegal", Tipo: "string", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "numero_tarjeta", Metodo: "WithNumeroTarjeta", Tipo: "int", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "periodo_entrega", Metodo: "WithPeriodoEntrega", Tipo: "string", Requerido: false, Etiqueta: "", Ejemplo: ""},
		},
		CamposDetalle: []CampoSector{
			{JSON: "cantidad_litros", Metodo: "WithCantidadLitros", Tipo: "float", Requerido: true, Etiqueta: "", Ejemplo: ""},
			{JSON: "porcentaje_deduccion_iehd_ds25530", Metodo: "WithPorcentajeDeduccionIehdDS25530", Tipo: "float", Requerido: false, Etiqueta: "", Ejemplo: ""},
		},
	},
	{
		Codigo:               45,
		Nombre:               "Comercial de Exportación Precio Venta",
		Layout:               "",
		TipoFacturaDocumento: 2,
		Operacion:            0,
		Fachada:              0,
		ConDetalle:           true,
		DetalleUnico:         false,
		DetallePar:           false,
		Soportado:            true,
		MontoSujetoIvaCero:   false,
		Campos: []CampoSector{
			{JSON: "cafc", Metodo: "WithCafc", Tipo: "string", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "codigo_excepcion", Metodo: "WithCodigoExcepcion", Tipo: "int", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "codigo_pais", Metodo: "WithCodigoPais", Tipo: "int", Requerido: true, Etiqueta: "", Ejemplo: ""},
			{JSON: "costos_gastos_internacionales", Metodo: "WithCostosGastosInternacionales", Tipo: "json", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "costos_gastos_nacionales", Metodo: "WithCostosGastosNacionales", Tipo: "json", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "descuento_adicional", Metodo: "WithDescuentoAdicional", Tipo: "float", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "direccion_comprador", Metodo: "WithDireccionComprador", Tipo: "string", Requerido: true, Etiqueta: "", Ejemplo: ""},
			{JSON: "incoterm", Metodo: "WithIncoterm", Tipo: "string", Requerido: true, Etiqueta: "", Ejemplo: ""},
			{JSON: "incoterm_detalle", Metodo: "WithIncotermDetalle", Tipo: "string", Requerido: true, Etiqueta: "", Ejemplo: ""},
			{JSON: "informacion_adicional", Metodo: "WithInformacionAdicional", Tipo: "string", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "lugar_destino", Metodo: "WithLugarDestino", Tipo: "string", Requerido: true, Etiqueta: "", Ejemplo: ""},
			{JSON: "monto_detalle", Metodo: "WithMontoDetalle", Tipo: "float", Requerido: true, Etiqueta: "", Ejemplo: ""},
			{JSON: "monto_total_sujeto_iva", Metodo: "WithMontoTotalSujetoIva", Tipo: "float", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "numero_descripcion_paquetes_bultos", Metodo: "WithNumeroDescripcionPaquetesBultos", Tipo: "json", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "numero_tarjeta", Metodo: "WithNumeroTarjeta", Tipo: "int", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "precio_valor_bruto", Metodo: "WithPrecioValorBruto", Tipo: "float", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "puerto_destino", Metodo: "WithPuertoDestino", Tipo: "string", Requerido: true, Etiqueta: "", Ejemplo: ""},
			{JSON: "total_gastos_internacionales", Metodo: "WithTotalGastosInternacionales", Tipo: "float", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "total_gastos_nacionales_fob", Metodo: "WithTotalGastosNacionalesFob", Tipo: "float", Requerido: true, Etiqueta: "", Ejemplo: ""},
		},
		CamposDetalle: []CampoSector{
			{JSON: "codigo_nandina", Metodo: "WithCodigoNandina", Tipo: "string", Requerido: true, Etiqueta: "", Ejemplo: ""},
		},
	},
	{
		Codigo:               46,
		Nombre:               "Sector Educativo Zona Franca",
		Layout:               "",
		TipoFacturaDocumento: 2,
		Operacion:            0,
		Fachada:              0,
		ConDetalle:           true,
		DetalleUnico:         false,
		DetallePar:           false,
		Soportado:            true,
		MontoSujetoIvaCero:   false,
		Campos: []CampoSector{
			{JSON: "nombre_estudiante", Metodo: "WithNombreEstudiante", Tipo: "string", Requerido: true, Etiqueta: "Nombre del estudiante", Ejemplo: "Juan Pérez"},
			{JSON: "periodo_facturado", Metodo: "WithPeriodoFacturado", Tipo: "string", Requerido: true, Etiqueta: "Período facturado", Ejemplo: "2026-08"},
			{JSON: "cafc", Metodo: "WithCafc", Tipo: "string", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "codigo_excepcion", Metodo: "WithCodigoExcepcion", Tipo: "int", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "descuento_adicional", Metodo: "WithDescuentoAdicional", Tipo: "float", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "monto_gift_card", Metodo: "WithMontoGiftCard", Tipo: "float", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "monto_total_sujeto_iva", Metodo: "WithMontoTotalSujetoIva", Tipo: "float", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "numero_tarjeta", Metodo: "WithNumeroTarjeta", Tipo: "int", Requerido: false, Etiqueta: "", Ejemplo: ""},
		},
	},
	{
		Codigo:               47,
		Nombre:               "Nota Crédito Débito Descuentos",
		Layout:               "",
		TipoFacturaDocumento: 3,
		Operacion:            1,
		Fachada:              6,
		ConDetalle:           true,
		DetalleUnico:         false,
		DetallePar:           true,
		Soportado:            true,
		MontoSujetoIvaCero:   false,
		Campos: []CampoSector{
			{JSON: "numero_autorizacion_cuf", Metodo: "WithNumeroAutorizacionCuf", Tipo: "string", Requerido: true, Etiqueta: "CUF de la factura original", Ejemplo: "7894561237894561237894561237894561237894561237894561237894561237894561AA"},
			{JSON: "fecha_emision_factura", Metodo: "WithFechaEmisionFactura", Tipo: "fecha", Requerido: true, Etiqueta: "Fecha de emisión de la factura original", Ejemplo: "2026-08-24T00:00:00.000"},
			{JSON: "monto_total_original", Metodo: "WithMontoTotalOriginal", Tipo: "float", Requerido: true, Etiqueta: "Monto total de la factura original", Ejemplo: "100.00"},
			{JSON: "monto_total_devuelto", Metodo: "WithMontoTotalDevuelto", Tipo: "float", Requerido: true, Etiqueta: "Monto devuelto por la nota", Ejemplo: "25.00"},
			{JSON: "monto_efectivo_credito_debito", Metodo: "WithMontoEfectivoCreditoDebito", Tipo: "float", Requerido: true, Etiqueta: "Monto efectivo de la nota", Ejemplo: "75.00"},
			{JSON: "monto_descuento_credito_debito", Metodo: "WithMontoDescuentoCreditoDebito", Tipo: "float", Requerido: false, Etiqueta: "Descuento de la nota", Ejemplo: "0.00"},
			{JSON: "numero_nota_credito_debito", Metodo: "WithNumeroNotaCreditoDebito", Tipo: "int", Requerido: false, Etiqueta: "Número de nota de crédito/débito", Ejemplo: "1"},
			{JSON: "codigo_excepcion", Metodo: "WithCodigoExcepcion", Tipo: "int", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "descuento_adicional", Metodo: "WithDescuentoAdicional", Tipo: "float", Requerido: false, Etiqueta: "", Ejemplo: ""},
		},
	},
	{
		Codigo:               48,
		Nombre:               "Nota Crédito Débito ICE",
		Layout:               "",
		TipoFacturaDocumento: 3,
		Operacion:            1,
		Fachada:              6,
		ConDetalle:           true,
		DetalleUnico:         false,
		DetallePar:           true,
		Soportado:            true,
		MontoSujetoIvaCero:   false,
		Campos: []CampoSector{
			{JSON: "numero_autorizacion_cuf", Metodo: "WithNumeroAutorizacionCuf", Tipo: "string", Requerido: true, Etiqueta: "CUF de la factura original", Ejemplo: "7894561237894561237894561237894561237894561237894561237894561237894561AA"},
			{JSON: "fecha_emision_factura", Metodo: "WithFechaEmisionFactura", Tipo: "fecha", Requerido: true, Etiqueta: "Fecha de emisión de la factura original", Ejemplo: "2026-08-24T00:00:00.000"},
			{JSON: "monto_total_original", Metodo: "WithMontoTotalOriginal", Tipo: "float", Requerido: true, Etiqueta: "Monto total de la factura original", Ejemplo: "100.00"},
			{JSON: "monto_total_devuelto", Metodo: "WithMontoTotalDevuelto", Tipo: "float", Requerido: true, Etiqueta: "Monto devuelto por la nota", Ejemplo: "25.00"},
			{JSON: "monto_efectivo_credito_debito", Metodo: "WithMontoEfectivoCreditoDebito", Tipo: "float", Requerido: true, Etiqueta: "Monto efectivo de la nota", Ejemplo: "75.00"},
			{JSON: "monto_descuento_credito_debito", Metodo: "WithMontoDescuentoCreditoDebito", Tipo: "float", Requerido: false, Etiqueta: "Descuento de la nota", Ejemplo: "0.00"},
			{JSON: "numero_nota_credito_debito", Metodo: "WithNumeroNotaCreditoDebito", Tipo: "int", Requerido: false, Etiqueta: "Número de nota de crédito/débito", Ejemplo: "1"},
			{JSON: "codigo_excepcion", Metodo: "WithCodigoExcepcion", Tipo: "int", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "descuento_adicional", Metodo: "WithDescuentoAdicional", Tipo: "float", Requerido: false, Etiqueta: "", Ejemplo: ""},
		},
		CamposDetalle: []CampoSector{
			{JSON: "alicuota_especifica", Metodo: "WithAlicuotaEspecifica", Tipo: "float", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "alicuota_iva", Metodo: "WithAlicuotaIva", Tipo: "float", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "alicuota_porcentual", Metodo: "WithAlicuotaPorcentual", Tipo: "float", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "cantidad_ice", Metodo: "WithCantidadIce", Tipo: "float", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "marca_ice", Metodo: "WithMarcaIce", Tipo: "int", Requerido: true, Etiqueta: "", Ejemplo: ""},
			{JSON: "monto_ice_especifico", Metodo: "WithMontoIceEspecifico", Tipo: "float", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "monto_ice_porcentual", Metodo: "WithMontoIcePorcentual", Tipo: "float", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "precio_neto_venta_ice", Metodo: "WithPrecioNetoVentaIce", Tipo: "float", Requerido: false, Etiqueta: "", Ejemplo: ""},
		},
	},
	{
		Codigo:               49,
		Nombre:               "Telecomunicaciones Zona Franca",
		Layout:               "",
		TipoFacturaDocumento: 2,
		Operacion:            0,
		Fachada:              2,
		ConDetalle:           true,
		DetalleUnico:         false,
		DetallePar:           false,
		Soportado:            true,
		MontoSujetoIvaCero:   false,
		Campos: []CampoSector{
			{JSON: "nit_conjunto", Metodo: "WithNitConjunto", Tipo: "int", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "cafc", Metodo: "WithCafc", Tipo: "string", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "codigo_excepcion", Metodo: "WithCodigoExcepcion", Tipo: "int", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "descuento_adicional", Metodo: "WithDescuentoAdicional", Tipo: "float", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "monto_gift_card", Metodo: "WithMontoGiftCard", Tipo: "float", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "numero_tarjeta", Metodo: "WithNumeroTarjeta", Tipo: "int", Requerido: false, Etiqueta: "", Ejemplo: ""},
		},
		CamposDetalle: []CampoSector{
			{JSON: "numero_imei", Metodo: "WithNumeroImei", Tipo: "string", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "numero_serie", Metodo: "WithNumeroSerie", Tipo: "string", Requerido: false, Etiqueta: "", Ejemplo: ""},
		},
	},
	{
		Codigo:               50,
		Nombre:               "Hospitales / Clínicas Zona Franca",
		Layout:               "",
		TipoFacturaDocumento: 2,
		Operacion:            0,
		Fachada:              0,
		ConDetalle:           true,
		DetalleUnico:         false,
		DetallePar:           false,
		Soportado:            true,
		MontoSujetoIvaCero:   false,
		Campos: []CampoSector{
			{JSON: "modalidad_servicio", Metodo: "WithModalidadServicio", Tipo: "string", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "cafc", Metodo: "WithCafc", Tipo: "string", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "codigo_excepcion", Metodo: "WithCodigoExcepcion", Tipo: "int", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "descuento_adicional", Metodo: "WithDescuentoAdicional", Tipo: "float", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "monto_gift_card", Metodo: "WithMontoGiftCard", Tipo: "float", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "monto_total_sujeto_iva", Metodo: "WithMontoTotalSujetoIva", Tipo: "float", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "numero_tarjeta", Metodo: "WithNumeroTarjeta", Tipo: "int", Requerido: false, Etiqueta: "", Ejemplo: ""},
		},
		CamposDetalle: []CampoSector{
			{JSON: "especialidad", Metodo: "WithEspecialidad", Tipo: "string", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "especialidad_detalle", Metodo: "WithEspecialidadDetalle", Tipo: "string", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "especialidad_medico", Metodo: "WithEspecialidadMedico", Tipo: "string", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "nit_documento_medico", Metodo: "WithNitDocumentoMedico", Tipo: "int", Requerido: true, Etiqueta: "", Ejemplo: ""},
			{JSON: "nombre_apellido_medico", Metodo: "WithNombreApellidoMedico", Tipo: "string", Requerido: true, Etiqueta: "", Ejemplo: ""},
			{JSON: "nro_factura_medico", Metodo: "WithNroFacturaMedico", Tipo: "int", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "nro_matricula_medico", Metodo: "WithNroMatriculaMedico", Tipo: "string", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "nro_quirofano_sala_operaciones", Metodo: "WithNroQuirofanoSalaOperaciones", Tipo: "int", Requerido: true, Etiqueta: "", Ejemplo: ""},
		},
	},
	{
		Codigo:               51,
		Nombre:               "Engarrafadoras",
		Layout:               "",
		TipoFacturaDocumento: 1,
		Operacion:            0,
		Fachada:              0,
		ConDetalle:           true,
		DetalleUnico:         false,
		DetallePar:           false,
		Soportado:            true,
		MontoSujetoIvaCero:   false,
		Campos: []CampoSector{
			{JSON: "cafc", Metodo: "WithCafc", Tipo: "string", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "codigo_excepcion", Metodo: "WithCodigoExcepcion", Tipo: "int", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "descuento_adicional", Metodo: "WithDescuentoAdicional", Tipo: "float", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "monto_total_sujeto_iva", Metodo: "WithMontoTotalSujetoIva", Tipo: "float", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "numero_tarjeta", Metodo: "WithNumeroTarjeta", Tipo: "int", Requerido: false, Etiqueta: "", Ejemplo: ""},
		},
	},
	{
		Codigo:               52,
		Nombre:               "Venta de Minerales al Banco Central (solo electrónica)",
		Layout:               "",
		TipoFacturaDocumento: 2,
		Operacion:            0,
		Fachada:              0,
		ConDetalle:           true,
		DetalleUnico:         false,
		DetallePar:           false,
		Soportado:            true,
		MontoSujetoIvaCero:   false,
		Modalidades:          []int{1},
		Campos: []CampoSector{
			{JSON: "cafc", Metodo: "WithCafc", Tipo: "string", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "codigo_excepcion", Metodo: "WithCodigoExcepcion", Tipo: "int", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "concentrado_granel", Metodo: "WithConcentradoGranel", Tipo: "string", Requerido: true, Etiqueta: "", Ejemplo: ""},
			{JSON: "descuento_adicional", Metodo: "WithDescuentoAdicional", Tipo: "float", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "direccion_comprador", Metodo: "WithDireccionComprador", Tipo: "string", Requerido: true, Etiqueta: "", Ejemplo: ""},
			{JSON: "gastos_realizacion", Metodo: "WithGastosRealizacion", Tipo: "float", Requerido: true, Etiqueta: "", Ejemplo: ""},
			{JSON: "humedad_porcentaje", Metodo: "WithHumedadPorcentaje", Tipo: "float", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "humedad_valor", Metodo: "WithHumedadValor", Tipo: "float", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "iva", Metodo: "WithIva", Tipo: "float", Requerido: true, Etiqueta: "", Ejemplo: ""},
			{JSON: "kilos_netos_humedos", Metodo: "WithKilosNetosHumedos", Tipo: "float", Requerido: true, Etiqueta: "", Ejemplo: ""},
			{JSON: "kilos_netos_secos", Metodo: "WithKilosNetosSecos", Tipo: "float", Requerido: true, Etiqueta: "", Ejemplo: ""},
			{JSON: "liquidacion_preliminar", Metodo: "WithLiquidacionPreliminar", Tipo: "float", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "merma_porcentaje", Metodo: "WithMermaPorcentaje", Tipo: "float", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "merma_valor", Metodo: "WithMermaValor", Tipo: "float", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "monto_gift_card", Metodo: "WithMontoGiftCard", Tipo: "float", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "numero_lote", Metodo: "WithNumeroLote", Tipo: "string", Requerido: true, Etiqueta: "", Ejemplo: ""},
			{JSON: "numero_tarjeta", Metodo: "WithNumeroTarjeta", Tipo: "int", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "origen", Metodo: "WithOrigen", Tipo: "string", Requerido: true, Etiqueta: "", Ejemplo: ""},
			{JSON: "otros_datos", Metodo: "WithOtrosDatos", Tipo: "string", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "sub_total", Metodo: "WithSubTotal", Tipo: "float", Requerido: true, Etiqueta: "", Ejemplo: ""},
		},
		CamposDetalle: []CampoSector{
			{JSON: "cantidad_extraccion", Metodo: "WithCantidadExtraccion", Tipo: "float", Requerido: true, Etiqueta: "", Ejemplo: ""},
			{JSON: "codigo_nandina", Metodo: "WithCodigoNandina", Tipo: "string", Requerido: true, Etiqueta: "", Ejemplo: ""},
			{JSON: "descripcion_leyes", Metodo: "WithDescripcionLeyes", Tipo: "string", Requerido: true, Etiqueta: "", Ejemplo: ""},
			{JSON: "unidad_medida_extraccion", Metodo: "WithUnidadMedidaExtraccion", Tipo: "int", Requerido: true, Etiqueta: "", Ejemplo: ""},
		},
	},
	{
		Codigo:               53,
		Nombre:               "Importación y Comercialización de Lubricantes IEHD",
		Layout:               "",
		TipoFacturaDocumento: 1,
		Operacion:            0,
		Fachada:              0,
		ConDetalle:           true,
		DetalleUnico:         false,
		DetallePar:           false,
		Soportado:            true,
		MontoSujetoIvaCero:   false,
		Campos: []CampoSector{
			{JSON: "cafc", Metodo: "WithCafc", Tipo: "string", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "ciudad", Metodo: "WithCiudad", Tipo: "string", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "codigo_excepcion", Metodo: "WithCodigoExcepcion", Tipo: "int", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "condicion_pago", Metodo: "WithCondicionPago", Tipo: "string", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "descuento_adicional", Metodo: "WithDescuentoAdicional", Tipo: "float", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "monto_deduccion_iehd_ds25530", Metodo: "WithMontoDeduccionIehdDS25530", Tipo: "float", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "monto_total_sujeto_iva", Metodo: "WithMontoTotalSujetoIva", Tipo: "float", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "nombre_propietario", Metodo: "WithNombrePropietario", Tipo: "string", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "nombre_representante_legal", Metodo: "WithNombreRepresentanteLegal", Tipo: "string", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "numero_tarjeta", Metodo: "WithNumeroTarjeta", Tipo: "int", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "periodo_entrega", Metodo: "WithPeriodoEntrega", Tipo: "string", Requerido: false, Etiqueta: "", Ejemplo: ""},
		},
		CamposDetalle: []CampoSector{
			{JSON: "cantidad_litros", Metodo: "WithCantidadLitros", Tipo: "float", Requerido: true, Etiqueta: "", Ejemplo: ""},
			{JSON: "porcentaje_deduccion_iehd_ds25530", Metodo: "WithPorcentajeDeduccionIehdDS25530", Tipo: "float", Requerido: false, Etiqueta: "", Ejemplo: ""},
		},
	},
	{
		Codigo:               54,
		Nombre:               "Compra-Venta de Insumos para Biodiésel",
		Layout:               "",
		TipoFacturaDocumento: 2,
		Operacion:            0,
		Fachada:              0,
		ConDetalle:           true,
		DetalleUnico:         false,
		DetallePar:           false,
		Soportado:            true,
		MontoSujetoIvaCero:   false,
		Campos: []CampoSector{
			{JSON: "cafc", Metodo: "WithCafc", Tipo: "string", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "codigo_excepcion", Metodo: "WithCodigoExcepcion", Tipo: "int", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "descuento_adicional", Metodo: "WithDescuentoAdicional", Tipo: "float", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "numero_tarjeta", Metodo: "WithNumeroTarjeta", Tipo: "int", Requerido: false, Etiqueta: "", Ejemplo: ""},
		},
	},
	{
		Codigo:               55,
		Nombre:               "Comercialización de Combustible",
		Layout:               "",
		TipoFacturaDocumento: 1,
		Operacion:            0,
		Fachada:              0,
		ConDetalle:           true,
		DetalleUnico:         false,
		DetallePar:           false,
		Soportado:            true,
		MontoSujetoIvaCero:   false,
		Campos: []CampoSector{
			{JSON: "cafc", Metodo: "WithCafc", Tipo: "string", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "codigo_autorizacion_sc", Metodo: "WithCodigoAutorizacionSC", Tipo: "string", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "codigo_excepcion", Metodo: "WithCodigoExcepcion", Tipo: "int", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "codigo_pais", Metodo: "WithCodigoPais", Tipo: "int", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "descuento_adicional", Metodo: "WithDescuentoAdicional", Tipo: "float", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "monto_total_sujeto_iva", Metodo: "WithMontoTotalSujetoIva", Tipo: "float", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "numero_tarjeta", Metodo: "WithNumeroTarjeta", Tipo: "int", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "observacion", Metodo: "WithObservacion", Tipo: "string", Requerido: false, Etiqueta: "", Ejemplo: ""},
			{JSON: "placa_vehiculo", Metodo: "WithPlacaVehiculo", Tipo: "string", Requerido: true, Etiqueta: "", Ejemplo: ""},
			{JSON: "tipo_envase", Metodo: "WithTipoEnvase", Tipo: "string", Requerido: false, Etiqueta: "", Ejemplo: ""},
		},
	},
}
