// Command buildergen generates statically typed calls against SDK constructors.
// Reflection is confined to this development tool; documents use compiled calls.
package main

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"reflect"
	"runtime"
	"sort"
	"strings"
)

func main() {
	var b bytes.Buffer
	fmt.Fprintln(&b, "// Code generated by go generate; DO NOT EDIT.\npackage siat")
	fmt.Fprintln(&b, `import "github.com/ron86i/go-siat/v2/pkg/models/invoices"`)
	sort.Slice(factories, func(i, j int) bool { return constructorName(factories[i]) < constructorName(factories[j]) })
	for _, f := range factories {
		name := constructorName(f)
		t := reflect.TypeOf(f).Out(0)
		fmt.Fprintf(&b, "func %s() *typedSDKBuilder {\n v:=invoices.%s()\n return &typedSDKBuilder{build:func() any{return v.Build()}, setters:map[string]func(any){\n", strings.ToLower(name[:1])+name[1:], name)
		for i := 0; i < t.NumMethod(); i++ {
			m := t.Method(i)
			if !strings.HasPrefix(m.Name, "With") && !strings.HasPrefix(m.Name, "Add") {
				continue
			}
			if m.Type.NumIn() != 2 {
				panic("unsupported SDK setter: " + name + "." + m.Name)
			}
			helper := "setBuilderValue"
			if m.Type.In(1).Kind() == reflect.Slice {
				helper = "setBuilderSlice"
			}
			if m.Type.IsVariadic() {
				helper = "setBuilderVariadic"
			}
			fmt.Fprintf(&b, "%q:func(value any){%s(v.%s,value)},\n", m.Name, helper, m.Name)
		}
		fmt.Fprintln(&b, "}}\n}")
	}
	source, err := format.Source(b.Bytes())
	if err != nil {
		panic(err)
	}
	path := "builder_calls_generated.go"
	if len(os.Args) > 1 {
		path = os.Args[1]
	}
	// JSON containers are validated in the domain before credential/SOAP calls.
	kinds := map[string]string{}
	for _, f := range factories {
		t := reflect.TypeOf(f).Out(0)
		for i := 0; i < t.NumMethod(); i++ {
			m := t.Method(i)
			if m.Type.NumIn() != 2 {
				continue
			}
			arg := m.Type.In(1)
			for arg.Kind() == reflect.Pointer {
				arg = arg.Elem()
			}
			switch arg.Kind() {
			case reflect.Map:
				kinds[m.Name] = "object"
			case reflect.Slice:
				kinds[m.Name] = "array"
			}
		}
	}
	var schema bytes.Buffer
	fmt.Fprintln(&schema, "// Code generated by go generate; DO NOT EDIT.\npackage fiscal\nvar sectorJSONKinds = map[string]string{")
	keys := make([]string, 0, len(kinds))
	for k := range kinds {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	for _, k := range keys {
		fmt.Fprintf(&schema, "%q:%q,\n", k, kinds[k])
	}
	fmt.Fprintln(&schema, "}")
	data, err := format.Source(schema.Bytes())
	if err != nil {
		panic(err)
	}
	schemaPath := filepath.Join(filepath.Dir(path), "../../domain/fiscal/sector_json_types_generated.go")
	if err = os.WriteFile(schemaPath, data, 0644); err != nil {
		panic(err)
	}
	if err = os.WriteFile(path, source, 0644); err != nil {
		panic(err)
	}
}
func constructorName(f any) string {
	name := runtime.FuncForPC(reflect.ValueOf(f).Pointer()).Name()
	return name[strings.LastIndex(name, ".")+1:]
}
