services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: invoig
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  api:
    build:
      context: ..
      dockerfile: docker/api.Dockerfile
    env_file:
      - ../apps/api/.env
    ports:
      - "3001:3001"
    depends_on:
      - postgres
      - redis

  admin:
    build:
      context: ..
      dockerfile: docker/admin.Dockerfile
    env_file:
      - ../apps/admin/.env.local
    ports:
      - "3000:3000"
    depends_on:
      - api
